# Generated by Django 2.2.4 on 2020-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filepdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Авторы')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('serius', models.CharField(blank=True, choices=[('mt', 'Математика'), ('ph', 'Физика'), ('bi', 'Биология'), ('ch', 'Химия'), ('pd', 'Педагогика'), ('lt', 'Литература'), ('ek', 'Экономика'), ('pr', 'Право')], default='mt', help_text='Серия публикации', max_length=2, verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['date'],
            },
        ),
    ]
