# Generated by Django 2.2.4 on 2020-04-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20200410_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='img_url',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
