# Generated by Django 2.2.4 on 2020-04-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_filepdf_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='img_url',
            field=models.FileField(upload_to='', verbose_name='Фото'),
        ),
    ]
